name: SKY UX Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @skyux-sdk/cli
      - run: npm i
      - run: npm test
      - run: npm run e2e
      - run: npm run build

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: echo I would publish!
        if: github.event.push
